language: node_js 
node_js: node

env:
  - ELM_VERSION=0.18.0 ELM_TEST=0.18.12

cache:
  directories
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts 
    - tests/elm-stuff/packages
    - stories/elm-stuff/build-artifacts 
    - stories/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm

before_install:
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - travis_retry elm package install --yes 

script:
  - elm-test --verbose
  - cd ./stories
  - ./createStories.sh
  - cd ../